root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -ldflags='-X github.com/android-sms-gateway/server/internal/version.AppVersion=dev -X github.com/android-sms-gateway/server/internal/version.AppRelease=1' -o ./tmp/main.exe ./cmd/sms-gateway"
  delay = 1000
  exclude_dir = ["api", "assets", "tmp", "vendor", "testdata", "tmp", "web"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yml"]
  kill_delay = "1s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
