export { default as Hero } from './Hero';
export { default as DemoVideo } from './DemoVideo';
export { default as SpeakWithBolu } from './SpeakWithBolu';
export { default as Stats } from './Stats';
export { default as Features } from './Features';
export { default as Benefits } from './Benefits';
export { default as Testimonials } from './Testimonials';
export { default as CTA } from './CTA';
export { default as FAQ } from './FAQ'; 